### ISSUE TITLE
How to validate Redirect URLs?

### ISSUE THREAD

**Issue by rdsubhas** [FrankHassanabad/Oauth2orizeRecipes#14]
Hi, Thanks so much for this wonderful demo. But right now, Clients are accepting *any* redirect URL, which is a huge problem (especially with implicit authorization).

Can you provide some tips/pointers on how to validate Redirect URLs? i.e. Each client has a list of allowed Redirect URLs, and authorize dialog requests must redirect to only those URLs. I tried, but couldn't find the right place to put this check...

**Comment by FrankHassanabad** [comment]
Oh man, I should have replied sooner.  The location of the warning is within

```
oauth2.js
```

```
// WARNING: For security purposes, it is highly advisable to check that
//          redirectURI provided by the client matches one registered with
//          the server.  For simplicity, this example does not.  You have
//          been warned.
return done(null, client, redirectURI);
```

Typically you do the validation based on the trusted clients that sign up.  They give you a URL for their redirect and you associate that with the client id they have also given you.

**Comment by rdsubhas** [comment]
Better late than never :) Thanks so much for this work @FrankHassanabad, it saved us a lot of time figuring out oauth2orize
