### ISSUE TITLE
Regards

### ISSUE THREAD

**Issue by MohamadAtieh** [FrankHassanabad/Oauth2orizeRecipes#15]
Thank you for taking the time explaining the differences between the strategies AND implementing them. I have implemented one of the strategies and modified the body to match my needs. Now, I am finalizing the tests and nothing really major is left. 

If you please can review the code and suggest any extra modifications or structure improvements? 

https://github.com/MohamadAtieh/node-endpoint

Thanks again!

**Comment by FrankHassanabad** [comment]
Hey, lots to learn when it comes to security, eh? :-)

Your project looks pretty cool.  I think it's easy to read and is easy enough for someone to pick up if they are interested.  Nothing sticks out to me within it but I didn't go through it with a fine tooth comb or anything.

I hope you implement more with it and try out more security hardening with it.

**Comment by MohamadAtieh** [comment]
@FrankHassanabad thanks for your fruitful thought...this is enough for me and I will make sure to extend it and have this repo as a reference in the future!

Thanks again

**Comment by FrankHassanabad** [comment]
Hey no problem.  I love to see others contributing and adding to different open source projects, especially the hard to figure out OAuth2 ones.
