### ISSUE TITLE
Examples don't run

### ISSUE THREAD

**Issue by nthsense** [FrankHassanabad/Oauth2orizeRecipes#16]
Installed the examples as instructed, but when Ioad them into the browser I get an "Error: no data received, ERR_EMPTY_RESPONSE".  Any ideas why this might be happening?

**Comment by referentiallytransparent** [comment]
@nthsense Instead of typing localhost:3000 in your browser, try https://localhost:3000/ instead

**Comment by FrankHassanabad** [comment]
Hopefully the comment above fixed your issue.  Closing this as a question for now.  Open a new one if you have any questions.
