### ISSUE TITLE
Automatic Authorization

### ISSUE THREAD

**Issue by igo88** [FrankHassanabad/Oauth2orizeRecipes#17]
Is there a way to authenticate users without the decisión?? (Screen where it ask the user to allow or not allow to access data).

**Comment by FrankHassanabad** [comment]
Yea, docs for the config setting are in [client.js](https://github.com/FrankHassanabad/Oauth2orizeRecipes/blob/master/authorization-server/db/clients.js#L15)

```
 trustedClient: (default if missing is false.  If this is set to true then the client is regarded as a
 trusted client and not a 3rd party application.  That means that the user will not be presented with
 a decision dialog with the trusted application and that the trusted application gets full scope access
 without the user having to make a decision to allow or disallow the scope access.
```

**Comment by igo88** [comment]
Thanks for your answer!! Its is working great.
I have another question but i will open another issue.

Thanks
