### ISSUE TITLE
oauth2 authorization code client implementation with react router ?

### ISSUE THREAD

**Issue by jitchavan** [FrankHassanabad/Oauth2orizeRecipes#19]
Hi,
we have created our own oauth 2 server with authorization code implementation from this code base.

but we are trying to integrate oauth2 client authentication in web application which includes react router and flux implementation. 

we looked into many git repositories but not getting any proper way to do this. 

is there any implementation which points us to how it can be achieved?

Thanks again.

**Comment by FrankHassanabad** [comment]
Can you make it work using plain javascript?  I would start there.
