### ISSUE TITLE
Storing on mongdb

### ISSUE THREAD

**Issue by taratoga** [FrankHassanabad/Oauth2orizeRecipes#20]
Filled in config\index.js:
exports.db = {
  timeToCheckExpiredTokens: 3600,
  type: "mongodb",
  dbName: "OAuth2orizeRecipeTokens"
};
exports.session = {
  type: "MongoStore",
  maxAge: 3600000 \* 24 \* 7 \* 52,
  //TODO You need to change this secret to something that you choose for your secret
  secret: "A Secret That Should Be Changed",
  dbName: "Session"
};

got this:
"D:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" app.js
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
Using MongoDB for the Session
Using MongoDB for the data store
OAuth 2.0 Authorization Server started on port 3000

and no connection to my standard configured Mongo Database..

Debugged the system:

Set a breakpoint to
mongoinit.js

 MongoClient.connect('mongodb://127.0.0.1:27017/' + config.db.dbName, function (err, db) {

but it dont comes to it...

Any idea whats happening hear.

If I put it back to memory based store everything works fine...

Oh I forgot I have updated last changes in the authorization server...

(refreshtoken,authorizationcodes,package)

**Comment by FrankHassanabad** [comment]
Been a while and I was busy for a while, and this got lost.  I am going to close this, but re-open this or another one if you still have questions.
