### ISSUE TITLE
Understanding Security Scenarios

### ISSUE THREAD

**Issue by anhldbk** [FrankHassanabad/Oauth2orizeRecipes#25]
In [Basic Authentication](https://github.com/FrankHassanabad/Oauth2orizeRecipes/wiki/Security-Scenarios#basic-authentication), would you pls tell me about this following step:

> Step 1, Send Basic auth user id and password with API call
> 
> ```
> GET product/API/endpoint HTTP/1.1
> Host: server.example.com
> Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
> ```

So you're sending the id & password via a `GET` call ? Where did you get the token `czZCaGRSa3F0MzpnWDFmQmF0M2JW`?

**Comment by anhldbk** [comment]
@FrankHassanabad If I guess correctly, in the section, you're trying to explain in detail about `OAuth grant types`, right? If so, there's [a wonderful article](https://stormpath.com/blog/what-the-heck-is-oauth) for that topic

**Comment by FrankHassanabad** [comment]
Sorry that I have been busy, but `czZCaGRSa3F0MzpnWDFmQmF0M2JW` in this case is a regular Basic Auth call which has the client id and client secret base64 encoded separated by a colon.  It's not a token.  That's the Basic Authentication specification.

I am actually considering tearing down this project and redoing it all over again...But utilizing ES6/Eslint and then using X.509 certificates, JWT's, and more security techniques way beyond what this project offers.

The problem has been not having time to re-write and put all of what I know down.
