### ISSUE TITLE
About Client Credentials Grant

### ISSUE THREAD

**Issue by anhldbk** [FrankHassanabad/Oauth2orizeRecipes#26]
In [authorization-server/oauth2.js, line 167](https://github.com/FrankHassanabad/Oauth2orizeRecipes/blob/master/authorization-server/oauth2.js#L167), we should verify clients' IDs and passwords before returning `access tokens`, right?

**Comment by FrankHassanabad** [comment]
Sorry for the late response.  Been too busy lately.

Yes that is correct.  I haven't looked at the code in quite a while though.  Looked now and I think it doesn't do any hooks in there for that as an example.
