### ISSUE TITLE
Generate a token for UUID for an iOS app in oauth2orize

### ISSUE THREAD

**Issue by jitchavan** [FrankHassanabad/Oauth2orizeRecipes#27]
We are using oauth2orize as our authentication server. We need to generate a token for an iOS app for its UUID/GUID. There is no default grant type for this.

Many people say to create our own grant type by using GrantTypeInterface.

The idea is something like this:
1. Create a guest user with Uuid and return a token.
2. Guest user can convert to customer user by registering himself.

are we doing/thinking this incorrectly?

**Comment by FrankHassanabad** [comment]
I know I haven't kept up on this project.  My apologies.  I would _not_ make a new grant type.  I would need to know more about your use case.  This doesn't seem like a normal OAuth2 flow you're mentioning here.
